[project]
name = "govuk-ai-accelerator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3==1.42.42",
    "flask==3.1.2",
    "flask-sqlalchemy==3.1.1",
    "psycopg2-binary==2.9.10",
    "pytest==8.3.4",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "s3fs==2026.2.0",
    "taxonomy-ontology-accelerator",
    "waitress==3.0.2",
]

[tool.uv.sources]
taxonomy-ontology-accelerator = { git = "https://github.com/alphagov/govuk-ai-accelerator-tw-accelerator.git", rev = "development" }
