"""Added config_data and domain_prompt

Revision ID: 17fafe2a9606
Revises: f256f73ad477
Create Date: 2026-03-19 13:17:00.175212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fafe2a9606'
down_revision = 'f256f73ad477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_data', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('domain_prompt', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_job', schema=None) as batch_op:
        batch_op.drop_column('domain_prompt')
        batch_op.drop_column('config_data')

    # ### end Alembic commands ###
